export const ERROR = 'ERROR';

export const FETCHED_INFO = 'FETCHED_INFO';
export const FETCHED_BALANCE = 'FETCHED_BALANCE';
export const FETCHED_UNCONFIRMED_BELDEX_TXS = 'FETCHED_UNCONFIRMED_BELDEX_TXS';
export const FETCHED_SWAPS = 'FETCHED_SWAPS';
export const TOKEN_SWAPPED = 'TOKEN_SWAPPED';
export const TOKEN_SWAP_FINALIZED = 'TOKEN_SWAP_FINALIZED';
