export const GET_INFO = 'GET_INFO';
export const GET_BALANCE = 'GET_BALANCE';
export const GET_UNCONFIRMED_BELDEX_TXS = 'GET_UNCONFIRMED_BELDEX_TXS';
export const GET_SWAPS = 'GET_SWAPS';
export const SWAP_TOKEN = 'SWAP_TOKEN';
export const FINALIZE_SWAP_TOKEN = 'FINALIZE_SWAP_TOKEN';
export const SEND_TRANSACTION_HASH = 'SEND_TRANSACTION_HASH';
export const SEND_TRANSACTION_ERROR_LOG = 'SEND_TRANSACTION_ERROR_LOG';

export const CONNECTED_WALLET_INFO="CONNECTED_WALLET_INFO";
export const POPUP_OPEN="POPUP_OPEN";
